port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
bind-address: "*"
mode: rule
# info / warning / error / debug / silent
log-level: error
# RESTful web API listening address
external-controller: 0.0.0.0:9090
secret: ''
# A relative path to the configuration directory or an absolute path to a
# directory in which you put some static web resource. Clash core will then
# serve it at `http://{{external-controller}}/ui`.
#external-ui: folder

# Outbound interface name
#interface-name: en0

# fwmark on Linux only
#routing-mark: 6666
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:7874
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - https://223.5.5.5/dns-query
  - https://doh.pub/dns-query
  - tls://dns.rubyfish.cn:853
  - dhcp://en0
  fallback:
  - 223.5.5.5
  - 119.29.29.29
  - 180.76.76.76
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
  fake-ip-filter:
  - +.nflxvideo.net
  - +.media.dssott.com

proxies:
{ProxyList}
proxy-groups:
  - name: 全局节点
    type: select
    proxies:
      - 最快节点
{ProxiesNames}
      - DIRECT
 
  - name: YouTube
    type: select
    proxies:
      - 最快节点
{ProxiesNames}
      - DIRECT

  - name: Netflix
    type: select
    proxies:
      - 最快节点
{ProxiesNames}
      - DIRECT

  - name: Amazon
    type: select
    proxies:
      - 最快节点
{ProxiesNames}
      - DIRECT

  - name: Disney
    type: select
    proxies:
      - 最快节点
{ProxiesNames}
      - DIRECT

  - name: 其它国际流媒体
    type: select
    proxies:
      - 最快节点
{ProxiesNames}
      - DIRECT

  - name: 未知流量
    type: select
    proxies:
      - DIRECT
      - 最快节点
{ProxiesNames}

  - name: 最快节点
    type: url-test
    proxies:
{ProxiesNames}
    url: https://www.gstatic.com/generate_204
    interval: 300

rule-providers:
#规则来自https://github.com/Loyalsoldier/clash-rules
  icloud:
    type: http
    behavior: domain
    url: https://mirror.ning.host/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: https://mirror.ning.host/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt
    path: ./ruleset/apple.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: https://mirror.ning.host/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: https://mirror.ning.host/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: https://mirror.ning.host/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: https://mirror.ning.host/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt
    path: ./ruleset/gfw.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: https://mirror.ning.host/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: https://mirror.ning.host/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: https://mirror.ning.host/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: https://mirror.ning.host/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: https://mirror.ning.host/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt
    path: ./ruleset/applications.yaml
    interval: 86400

#规则来自https://github.com/ningjx/Clash-Rules
#git 加速 gh.con.sh ghproxy.com
  streaming:
    type: http
    behavior: classical
    url: https://mirror.ning.host/https://raw.githubusercontent.com/ningjx/Clash-Rules/master/Streaming.txt
    path: ./ruleset/Streaming.yaml
    interval: 86400

  netflix:
    type: http
    behavior: classical
    url: https://mirror.ning.host/https://raw.githubusercontent.com/ningjx/Clash-Rules/master/auto_generate/Netflix.txt
    path: ./ruleset/Netflix.list
    interval: 86400

  amazon:
    type: http
    behavior: classical
    url: https://mirror.ning.host/https://raw.githubusercontent.com/ningjx/Clash-Rules/master/auto_generate/PrimeVideo.txt
    path: ./ruleset/Amazon.list
    interval: 86400

  youtube:
    type: http
    behavior: classical
    url: https://mirror.ning.host/https://raw.githubusercontent.com/ningjx/Clash-Rules/master/auto_generate/YouTube.txt
    path: ./ruleset/YouTube.list
    interval: 86400

  disney:
    type: http
    behavior: classical
    url: https://mirror.ning.host/https://raw.githubusercontent.com/ningjx/Clash-Rules/master/auto_generate/Disney.txt
    path: ./ruleset/Disney.list
    interval: 86400

  customdirect:
    type: http
    behavior: classical
    url: https://mirror.ning.host/https://raw.githubusercontent.com/ningjx/Clash-Rules/master/CustomDirect.txt
    path: ./ruleset/CustomDirect.list
    interval: 86400

  customproxy:
    type: http
    behavior: classical
    url: https://mirror.ning.host/https://raw.githubusercontent.com/ningjx/Clash-Rules/master/CustomProxy.txt
    path: ./ruleset/CustomProxy.list
    interval: 86400

rules:
  - RULE-SET,customproxy,全局节点
  - RULE-SET,netflix,Netflix
  - RULE-SET,youtube,YouTube
  - RULE-SET,amazon,Amazon
  - RULE-SET,disney,Disney
  - RULE-SET,streaming,其它国际流媒体
  - RULE-SET,proxy,全局节点
  - RULE-SET,telegramcidr,全局节点
  
  - RULE-SET,customdirect,DIRECT
  - RULE-SET,applications,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - GEOIP,LAN,DIRECT,no-resolve
  #- GEOIP,CN,DIRECT
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,未知流量
