name: pull_ACL4SSR_netflix.list

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "netflix_ip=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetflixIP.list" >> $GITHUB_ENV
        shell: bash
        
        
      - name: Generate NetflixIP.txt file
        run: |
          echo "payload:" > NetflixIP.txt
          curl -sSL ${netflix_ip} | grep -E "^IP-CIDR" | awk -F ' ' '{printf "  - |+.%s|\n", $1}' | sed "s/|/'/g" >> NetflixIP.txt
          
      - name: Move files
        run: |
          mkdir -p NetflixRules
          cp *.txt ./NetflixRules/
          
      - name: Commit
        run: |
          git init
          git config --local user.name "ningjx"
          git config --local user.email "ninglogin@gmail.com"
          #git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin master
          done
